apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    chart-version: {{ .Chart.Version }}
  name: {{ .Chart.Name }}-configmap
data:
  APP_NAME: "{{ .Chart.Name }}"
  SPRING_PROFILES_ACTIVE: "{{ .Values.environment }}"
