apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Chart.Name }}
  name: {{ .Release.Name }}
spec:
  type: ClusterIP
  ipFamilies:
    - IPv4
  ports:
    - name: 8080-tcp
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: {{ .Release.Name }}
    deployment: {{ .Release.Name }}
  sessionAffinity: None
