package eu.europa.ec.simpl.contracts.kafka;

public enum KafkaTopic {

    SIGN_CONTRACT_REQUEST,
    SIGN_CONTRACT_RESPONSE,
    STATUS_UPDATE,
    SEARCH_ACTIVE_CONTRACT_REQUEST,
    SEARCH_ACTIVE_CONTRACT_RESPONSE,
    CREATE_CONTRACT_REQUEST,
    CREATE_CONTRACT_RESPONSE;
}
